# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    image: postgis/postgis:12-2.5
    container_name: open-inwoner-db
    environment:
      - POSTGRES_USER=${DB_USER:-open_inwoner}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-open_inwoner}
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORTS:-9201:9201}

  redis:
    image: redis

  web:
    build: .
    container_name: open-inwoner-web
    environment:
      - DJANGO_SETTINGS_MODULE=open_inwoner.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7bk)w=_%lnm#68rc!c)h@gy&5+%^fl=okq17bv!)yv!l0udu2y}
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - ES_HOST=elasticsearch
      - DISABLE_2FA=${DISABLE_2FA:-True}
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - elasticsearch

volumes:
  db_data:
  es_data:
